// Regenerate both a fresh demo seed and a targeted update for an existing demo.
// Run from the repository root: deno run --allow-read --allow-write supabase/scripts/build_bird_seed.ts
interface Bird {
  species: string;
  displayName: string;
  username: string;
  posts: string[];
}

interface PostImage {
  species: string;
  postIndex: number;
  file: string;
  prompt: string;
}

const birds: Bird[] = JSON.parse(await Deno.readTextFile("supabase/demo/birds.json"));
const postImages: PostImage[] = JSON.parse(await Deno.readTextFile("supabase/assets/post-prompts.json"));
const imageFiles = new Map<string, string>();
const uniqueFiles = new Set<string>();
for (const image of postImages) {
  const bird = birds.find((bird) => bird.species === image.species);
  const key = `${image.species}:${image.postIndex}`;
  if (
    !bird || !Number.isInteger(image.postIndex) || image.postIndex < 0 || image.postIndex >= bird.posts.length ||
    !/^[a-z-]+-v\d+\.jpg$/.test(image.file) || imageFiles.has(key) || uniqueFiles.has(image.file)
  ) {
    throw new Error(`Invalid or duplicate post image: ${key}`);
  }
  const asset = await Deno.stat(`supabase/assets/posts/${image.file}`);
  if (!asset.isFile || asset.size === 0 || asset.size > 1048576) {
    throw new Error(`Post image is empty or exceeds bucket limit: ${image.file}`);
  }
  imageFiles.set(key, image.file);
  uniqueFiles.add(image.file);
}
const baseURL = "https://ncmomgqxdwrjwmoihayz.supabase.co";
const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;
const profileID = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const postID = (n: number) => `10000000-0000-4000-8000-${String(n).padStart(12, "0")}`;

if (birds.length !== 15 || new Set(birds.map((bird) => bird.username)).size !== 15) {
  throw new Error("The demo requires 15 distinct bird profiles.");
}
const allPosts = new Set<string>();
for (const bird of birds) {
  if (!/^[a-z]+$/.test(bird.species) || bird.posts.length !== 8 || bird.username.length > 30) {
    throw new Error(`Invalid bird profile: ${bird.species}`);
  }
  const avatar = await Deno.stat(`supabase/assets/avatars/${bird.species}-v1.jpg`);
  if (avatar.size > 262144) throw new Error(`Avatar exceeds bucket limit: ${bird.species}`);
  for (const text of bird.posts) {
    if (text !== text.trim() || Array.from(text).length < 1 || Array.from(text).length > 300 || allPosts.has(text)) {
      throw new Error(`Invalid or duplicate post for ${bird.species}: ${text}`);
    }
    allPosts.add(text);
  }
}

const profileRows = birds.map((bird, index) =>
  `(${quote(profileID(index + 1))},${quote(bird.username)},${quote(bird.displayName)},` +
  `${quote(`${baseURL}/storage/v1/object/public/chirpy-avatars/${bird.species}-v1.jpg`)})`
).join(",\n");
// Interleave the voices; retain original IDs, author assignments, and six tied timestamps.
const postRows = Array.from({ length: 120 }, (_, index) => {
  const bird = birds[index % 15];
  const postIndex = Math.floor(index / 15);
  const imageFile = imageFiles.get(`${bird.species}:${postIndex}`);
  const imageURL = imageFile ? quote(`${baseURL}/storage/v1/object/public/chirpy-posts/${imageFile}`) : "null";
  return `(${quote(postID(index + 1))},${quote(profileID(index % 15 + 1))},` +
    `${quote(bird.posts[postIndex])},${imageURL})`;
}).join(",\n");

const seed =
  `-- Generated by supabase/scripts/build_bird_seed.ts; edit supabase/demo/birds.json and supabase/assets/post-prompts.json.
-- Deterministic demo IDs. The shared posting identity is Pip Sparrow (@crumbclub).
begin;
insert into public.profiles (id, username, display_name, avatar_url)
values
${profileRows}
on conflict (id) do update set username=excluded.username, display_name=excluded.display_name, avatar_url=excluded.avatar_url;

insert into public.posts (id, author_id, body, image_url, created_at)
select id::uuid, author_id::uuid, body, image_url,
  case when n between 1 and 6 then '2026-08-31T18:42:00Z'::timestamptz
       else '2026-08-31T18:42:00Z'::timestamptz - ((n - 6) * interval '7 hours') end
from (values
${postRows}
) as demo(id, author_id, body, image_url)
cross join lateral (select right(id, 12)::integer as n) as sequence
on conflict (id) do update set author_id=excluded.author_id, body=excluded.body, image_url=excluded.image_url;

insert into public.likes (user_id, post_id, created_at)
select
  ('00000000-0000-4000-8000-' || lpad(u::text, 12, '0'))::uuid,
  ('10000000-0000-4000-8000-' || lpad(p::text, 12, '0'))::uuid,
  '2026-08-31T19:00:00Z'::timestamptz
from generate_series(1, 15) u
cross join generate_series(1, 120) p
where (u * 7 + p * 3) % 17 < 3
on conflict do nothing;
commit;
`;

const update =
  `-- Generated by supabase/scripts/build_bird_seed.ts; edit supabase/demo/birds.json and supabase/assets/post-prompts.json.
-- Updates only existing seeded records. Preserves timestamps, likes, and user-created posts.
begin;
update public.profiles p
set username = demo.username, display_name = demo.display_name, avatar_url = demo.avatar_url
from (values
${profileRows}
) as demo(id, username, display_name, avatar_url)
where p.id = demo.id::uuid;

update public.posts p
set author_id = demo.author_id::uuid, body = demo.body, image_url = demo.image_url
from (values
${postRows}
) as demo(id, author_id, body, image_url)
where p.id = demo.id::uuid;
commit;
`;

for (const [path, content] of [["supabase/seed.sql", seed], ["supabase/demo/refresh-bird-demo.sql", update]]) {
  if (Deno.args.includes("--check")) {
    if (await Deno.readTextFile(path) !== content) throw new Error(`Regenerate ${path}`);
  } else {
    await Deno.writeTextFile(path, content);
  }
}
console.log(
  `Validated ${birds.length} avatars, ${allPosts.size} unique bird posts, and ${postImages.length} post images.`,
);
